# Generated by Django 3.2.9 on 2021-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='employees',
            new_name='number_of_employees',
        ),
    ]
