# Generated by Django 3.2.9 on 2021-11-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211107_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='name_and_surname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
    ]
