# Generated by Django 3.2.9 on 2021-11-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='event_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_coordinator', to='courses.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer', to='courses.person'),
        ),
    ]
